Repository pangeo-forge/staged-recipes, pull requests merged in 2022-09, with the labels that each got.

#106 Cleanup: remove old recipes
  recipes/.gitignore
  recipes/CMIP6_static_grids/meta.yaml
  recipes/CMIP6_static_grids/recipe.py
  recipes/HadISST/meta.yaml
  recipes/HadISST/recipe.py
  recipes/README.md
  recipes/WOA_1degree_monthly/meta.yaml
  recipes/WOA_1degree_monthly/recipe.py
  recipes/cesm-atm-025deg/meta.yaml
  recipes/cesm-atm-025deg/recipe.py
  recipes/cmip6/meta.yaml
  recipes/cmip6/recipe.py
  recipes/gpcp/meta.yaml
  recipes/gpcp/recipe.py
  recipes/gpm-imerg/meta.yaml
  recipes/gpm-imerg/recipe.py
  recipes/gridmet/meta.yaml
  recipes/gridmet/recipe.py
  recipes/noaa-coastwatch-geopolar-sst/meta.yaml
  recipes/noaa-coastwatch-geopolar-sst/recipe.py
  recipes/noaa-oisst/meta.yaml
  recipes/noaa-oisst/recipe.py
  recipes/osm-tutorial-demonstration/meta.yaml
  recipes/osm-tutorial-demonstration/recipe.py
  recipes/paleo-pism/meta.yaml
  recipes/paleo-pism/recipe.py
  recipes/riops/meta.yaml
  recipes/riops/recipe.py
  recipes/terraclimate/meta.yaml
  recipes/terraclimate/recipe.py
  recipes/test-000-dataset/meta.yaml
  recipes/test-000-dataset/recipe.py
  recipes/test-oisst-1/meta.yaml
  recipes/test-oisst-1/recipe.py
  recipes/test-oisst-2/meta.yaml
  recipes/test-oisst-2/recipe.py
  setup.cfg
Labels: not-recipe

#88 simplify pre-commit
  .github/ISSUE_TEMPLATE/proposed-recipe.md
  .github/ISSUE_TEMPLATE/proposed-recipe.yaml
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/pre-commit.yaml
  .pre-commit-config.yaml
  .prettierrc.toml
  README.md
  pyproject.toml
  setup.cfg
Labels: not-recipe

#162 Add first split CMIP6 feedstock
  recipes/CMIP6-PMIP/meta.yaml
  recipes/CMIP6-PMIP/recipe.py
  recipes/CMIP6-PMIP/requirements.txt
Labels: blocked:runner-image, blocked:external-dependency

#190 Add GPM IMERG Late Precipitation Daily recipe
  .DS_Store
  recipes/.DS_Store
  recipes/GPM_3IMERGDL/meta.yaml
  recipes/GPM_3IMERGDL/recipe.py
Labels: blocked:credentials

#176 C-iTRACE d18O recipe
  recipes/eVolv2k_v3/meta.yaml
  recipes/eVolv2k_v3/recipe.py
Labels: blocked:github-app-feature
